name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyze iOS app
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies (CocoaPods)
        run: |
          if [ -f "Podfile" ]; then
            sudo gem install cocoapods
            pod install
          fi

      - name: Build
        env:
          scheme: "habit tracker"  
        run: |
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          xcodebuild clean build analyze -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination 'platform=iOS Simulator,name=iPhone 14,OS=18.1' | xcpretty && exit ${PIPESTATUS[0]}

      - name: Boot simulator
        run: xcrun simctl boot "iPhone 14"

      - name: Run on simulator (headless)
        run: |
          xcodebuild test -scheme "habit tracker" -destination 'platform=iOS Simulator,name=iPhone 14,OS=18.1' -destination-timeout 30
        timeout-minutes: 5
